# Generated by Django 2.2.3 on 2019-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice_name', models.CharField(max_length=200, verbose_name='公告题目')),
                ('Notice_text', models.TextField(verbose_name='公告内容')),
                ('pub_date', models.DateTimeField(verbose_name='公告时间')),
            ],
        ),
    ]
