# Generated by Django 2.1.5 on 2019-08-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_one_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='队员一ID')),
                ('team_member_two_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='队员二ID')),
                ('is_school', models.NullBooleanField(verbose_name='是否为本校学生')),
                ('is_freshman', models.NullBooleanField(verbose_name='是否为本校新生')),
                ('team_member_one_school_ID', models.CharField(blank=True, max_length=50, null=True, verbose_name='队员一学号')),
                ('team_member_two_school_ID', models.CharField(blank=True, max_length=50, null=True, verbose_name='队员二学号')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
