# Generated by Django 2.2.3 on 2019-07-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='is_school',
            field=models.NullBooleanField(verbose_name='是否为本校学生'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_member_one_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='队员一ID'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_member_one_school_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='队员一学号'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_member_two_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='队员二ID'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_member_two_school_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='队员二学号'),
        ),
    ]
