# Generated by Django 2.1.5 on 2019-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190716_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='is_school',
            field=models.NullBooleanField(verbose_name='是否为本校大一学生'),
        ),
    ]
