# Generated by Django 2.2.3 on 2019-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190719_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='is_freshman',
            field=models.NullBooleanField(verbose_name='是否为大一学生'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='is_school',
            field=models.NullBooleanField(verbose_name='是否为本校学生'),
        ),
    ]
