# Generated by Django 2.1.5 on 2019-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190722_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='is_freshman',
        ),
        migrations.AlterField(
            model_name='teams',
            name='is_school',
            field=models.NullBooleanField(verbose_name='是否为本校大一学生'),
        ),
    ]
