# Generated by Django 2.1.5 on 2019-07-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190725_2147'),
        ('accounts', '0006_auto_20190725_2235'),
    ]

    operations = [
    ]
