# Generated by Django 2.1.5 on 2019-09-21 12:07

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190921_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
