# Generated by Django 2.1.5 on 2019-08-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='', verbose_name='出题人头像')),
                ('name', models.CharField(max_length=20, verbose_name='出题人')),
                ('QQ', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='题目')),
                ('content', models.TextField(verbose_name='正文')),
                ('link', models.CharField(default=' ', max_length=500, null=True, verbose_name='题目地址')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='最后一次修改时间')),
                ('hints', models.TextField(blank=True, verbose_name='提示')),
                ('flag', models.CharField(default='', max_length=30)),
                ('state', models.IntegerField(choices=[(0, 'hidden'), (1, 'obvious')], default=0, verbose_name='是否隐藏')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='分数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Author', verbose_name='出题人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Category', verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_challenge_id', to='challenge.Challenge')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
