# Generated by Django 2.2.3 on 2019-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='hints',
            field=models.TextField(blank=True, verbose_name='提示'),
        ),
    ]
