# Generated by Django 2.1.5 on 2019-09-21 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 11, 15, 3, 920164, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间'),
        ),
    ]
