# Generated by Django 2.1.5 on 2019-09-21 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20190921_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 11, 39, 52, 833313, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
