# Generated by Django 2.2.3 on 2019-07-22 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190719_2116'),
        ('challenge', '0003_auto_20190716_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='flag',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='题目'),
        ),
        migrations.CreateModel(
            name='solves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_challenge_id', to='challenge.Challenge')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='accounts.Teams')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='flag')),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_challenge_id', to='challenge.Challenge')),
            ],
        ),
    ]
