# Generated by Django 2.2.3 on 2019-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20190722_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='challenge',
            name='state',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'obvious')], default=0, verbose_name='是否隐藏'),
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
