# Generated by Django 2.2.3 on 2019-07-22 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190719_2116'),
        ('challenge', '0005_auto_20190722_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='solves',
            new_name='Solve',
        ),
    ]
