# Generated by Django 2.2.3 on 2019-07-22 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20190722_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='solve',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
