# Generated by Django 2.2.3 on 2019-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20190722_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='分数'),
        ),
    ]
