# Generated by Django 2.2.3 on 2019-07-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_challenge_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
