# Generated by Django 2.2.3 on 2019-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(null=True, upload_to='media', verbose_name='上传文件')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='文件名称')),
            ],
        ),
    ]
