# Generated by Django 2.2.3 on 2019-07-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
